# Generated by Django 3.2.12 on 2022-07-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creador',
        ),
    ]
